### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by lamarios** [datamate-rethink-it/n8n-nodes-seafile#1]
Hi, I'm trying to install this package via the UI and i get this error (from logs)

```
Error loading package "n8n-nodes-seafile" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
ResponseError: Error loading package "n8n-nodes-seafile" :The specified package could not be loaded
Cause: Class could not be found. Please check if the class is named correctly.
    at CommunityPackagesController.installPackage (/usr/local/lib/node_modules/n8n/dist/controllers/community-packages.controller.js:81:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at handler (/usr/local/lib/node_modules/n8n/dist/decorators/controller.registry.js:93:24)
    at /usr/local/lib/node_modules/n8n/dist/response-helper.js:110:26
```

n8n version 1.72.1

**Comment by magicmex** [comment]
+1
```
Error installing new package

Error loading package "n8n-nodes-seafile" :The specified package could not be loaded Cause: Class could not be found. Please check if the class is named correctly.
```

**Comment by ZxBing0066** [comment]
💡 It looks like the issue is caused by Community Node conflicts.
To resolve it, try clearing the `/home/node/.n8n/nodes` folder and then restart `n8n`.

For a detailed explanation and steps, check out my blog post(in Chinese):  
👉 [How to solve "Class could not be found" in n8n](https://blog.heyfe.org/blog/n8n-node-install-error)
